# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u3g_r1fSTvViEEcuruv-bu8pykdQ6Sm_
"""

print("Hello World")

print("你好嗎")

print("Hello World")
print("你好嗎")

